name: Build and Test

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'action.yml'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      
      - name: Build
        run: npm run build
      
      - name: Check for dist changes
        id: diff
        run: |
          git add dist/
          git diff --staged --quiet dist/ || echo "changes=true" >> $GITHUB_OUTPUT
      
      - name: Commit dist if changed
        if: github.event_name != 'pull_request' && steps.diff.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "chore: update dist" -a
          git push
